# Generated by Django 3.2.25 on 2025-06-01 11:48

from django.db import migrations


def migrate_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    
    for flat in Flat.objects.iterator():
        owner, _ = Owner.objects.get_or_create(
            full_name=flat.owner,
            defaults={
                'owners_phonenumber': flat.owners_phonenumber,
                'owner_pure_phone': flat.owner_pure_phone
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20250529_2143'),
    ]

    operations = [
        migrations.RunPython(migrate_owners),
    ]
